//
// Created by mathe on 09/03/2020.
//

#ifndef RAYTRACER_SRC_CORE_PARAM_SET_PARAM_SET_HPP_
#define RAYTRACER_SRC_CORE_PARAM_SET_PARAM_SET_HPP_

class ParamSet {

};

#endif //RAYTRACER_SRC_CORE_PARAM_SET_PARAM_SET_HPP_
