//
// Created by mathe on 09/03/2020.
//

#ifndef RAYTRACER_SRC_CORE_PARAM_SET_PARAM_ARRAY_ITEM_HPP_
#define RAYTRACER_SRC_CORE_PARAM_SET_PARAM_ARRAY_ITEM_HPP_

class param_array_item {

};

#endif //RAYTRACER_SRC_CORE_PARAM_SET_PARAM_ARRAY_ITEM_HPP_
