//
// Created by matheus_rangel on 12/03/2020.
//

#ifndef RAYTRACER_SRC_CORE_BACKGROUND_BACKGROUND_FACTORY_H_
#define RAYTRACER_SRC_CORE_BACKGROUND_BACKGROUND_FACTORY_H_

class BackgroundFactory {

};

#endif //RAYTRACER_SRC_CORE_BACKGROUND_BACKGROUND_FACTORY_H_
